### ISSUE TITLE
Add CI and analysis to the GitHub depot

### ISSUE THREAD

**Issue by jairbubbles** [fastbuild/fastbuild#150]
Hello, I think it will be very cool to have continuous builds with AppVeyor or TravisCI. I I haven't setup something like this but it doesn't seem too complex. I don't know if they offer all environments that are targeted by fastbuild. I can spend some time to investigate if you're interested.

Also, SonarSube analysis is now available for open source projects (https://about.sonarqube.com/news/2016/09/01/sonarqubedotcom-open-to-aynone.html).  In my last merge request (orbis prx) it would have been pretty cool as it should have detected my code duplication and forbade the pull request. That example show that behavior https://github.com/bellingard/multi-language-project/pull/5.

You can add tags on the project page too.

**Comment by ffulin** [comment]
I'd love to have some automated CI, and I've looked into Travis CI previously. I took another look just now. The issues are as follows:
 - No Windows support.  Most development is done on Windows. Travis CI doesn't support Windows. It might still be worth the coverage on OSX and Linux.
 - FASTBuild support.  FASTBuild is built using itself, but it's not clear if Travis CI supports that (it seems to be very make/scons centric).

As for static analysis, I'm a fan of that as well.  I looked at Sonarqube briefly, but I couldn't get it to do anything useful after signing in with GitHub.  I'll look into it again soon.

**Comment by jairbubbles** [comment]
Well AppVeyor does support windows and it seems pretty neat.
When looking at the documentation https://www.appveyor.com/docs/build-configuration/ it seems you can launch cmd and power shell commands so I guess you can do whatever you want.
There is also support for chocolatey packages. If you make one for fastbuild you could retrieve it on the worker at the beginning of the build.

**Comment by ffulin** [comment]
Nice.  I had looked at AppVeyor and for some reason I thought it was a C# only thing, but it does seem to support C++.

Definitely some interesting options here.

**Comment by jairbubbles** [comment]
I tested with a very simple project and it's quite easy to setup. I only had to specify I wanted VS2015 and add a pre-build nuget step.
You can checkout my config file here https://github.com/jairbubbles/BitmapFont/blob/master/appveyor.yml

To download and unzip latest version in powershell:
```
install:
  - ps: (new-object net.webclient).DownloadFile('http://fastbuild.org/downloads/v0.91/FASTBuild-Windows-x64-v0.91.zip', 'FASTBuild.zip')
  - ps: Add-Type -assembly “system.io.compression.filesystem”
  - ps: [io.compression.zipfile]::ExtractToDirectory('FastBuild.Zip', 'FastBuild')
```

 I'll try to make a SonarQube scan now and let you know. The documentation is indeed very light.
